### ISSUE TITLE
ImportError: No module named submin

### ISSUE THREAD

**Issue by alager** [mjholtkamp/submin#5]
Just ran ubuntu updates and something broke submin.

Here are the dpkg.log entries.
```
2016-12-07 10:00:01 upgrade submin2-core:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:01 status half-configured submin2-core:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-core:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-core:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-core:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-core:all 2.2.2-1
2016-12-07 10:00:02 status unpacked submin2-core:all 2.2.2-1
2016-12-07 10:00:02 upgrade submin2-svn:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:02 status half-configured submin2-svn:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-svn:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-svn:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-svn:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-svn:all 2.2.2-1
2016-12-07 10:00:02 status unpacked submin2-svn:all 2.2.2-1
2016-12-07 10:00:02 upgrade submin2-git:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:02 status half-configured submin2-git:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-git:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-git:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-git:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-git:all 2.2.2-1
2016-12-07 10:00:02 status unpacked submin2-git:all 2.2.2-1
2016-12-07 10:00:02 upgrade submin2-trac:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:02 status half-configured submin2-trac:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-trac:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-trac:all 2.2.1-1
2016-12-07 10:00:02 status half-installed submin2-trac:all 2.2.1-1
2016-12-07 10:00:02 status unpacked submin2-trac:all 2.2.2-1
2016-12-07 10:00:02 status unpacked submin2-trac:all 2.2.2-1
2016-12-07 10:00:03 upgrade submin2-full:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:03 status half-configured submin2-full:all 2.2.1-1
2016-12-07 10:00:03 status unpacked submin2-full:all 2.2.1-1
2016-12-07 10:00:03 status half-installed submin2-full:all 2.2.1-1
2016-12-07 10:00:03 status half-installed submin2-full:all 2.2.1-1
2016-12-07 10:00:03 status unpacked submin2-full:all 2.2.2-1
2016-12-07 10:00:03 status unpacked submin2-full:all 2.2.2-1
2016-12-07 10:00:03 upgrade submin2:all 2.2.1-1 2.2.2-1
2016-12-07 10:00:03 status half-configured submin2:all 2.2.1-1
2016-12-07 10:00:03 status unpacked submin2:all 2.2.1-1
2016-12-07 10:00:03 status half-installed submin2:all 2.2.1-1
2016-12-07 10:00:03 status half-installed submin2:all 2.2.1-1
2016-12-07 10:00:03 status unpacked submin2:all 2.2.2-1
2016-12-07 10:00:03 status unpacked submin2:all 2.2.2-1
```

```
2016-12-07 10:01:25 configure submin2-core:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2-core:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2-core:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2-core:all 2.2.2-1
2016-12-07 10:01:25 configure submin2-svn:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2-svn:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2-svn:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2-svn:all 2.2.2-1
2016-12-07 10:01:25 configure submin2-git:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2-git:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2-git:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2-git:all 2.2.2-1
2016-12-07 10:01:25 configure submin2-trac:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2-trac:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2-trac:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2-trac:all 2.2.2-1
2016-12-07 10:01:25 configure submin2-full:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2-full:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2-full:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2-full:all 2.2.2-1
2016-12-07 10:01:25 configure submin2:all 2.2.2-1 <none>
2016-12-07 10:01:25 status unpacked submin2:all 2.2.2-1
2016-12-07 10:01:25 status half-configured submin2:all 2.2.2-1
2016-12-07 10:01:25 status installed submin2:all 2.2.2-1
```

Whenever I try to run submin2-admin comands I get: 
```
$ submin2-admin /var/lib/submin help
Traceback (most recent call last):
  File "/usr/bin/submin2-admin", line 2, in <module>
    import submin, sys
ImportError: No module named submin
```

In `conf-enabled/apache-webui-cgi.conf` and `conf-enabled/apache-svn.conf` I noticed that the paths were to `/usr/lib/python2.7/dist-packages` whereas the files appear to now live in `/usr/lib/python2.7/site-packages`.  

I tried updating the paths, but now I get a server 500 error:
```
[Fri Dec 09 09:48:27.911255 2016] [core:notice] [pid 13566] AH00094: Command line: '/usr/sbin/apache2'
[Fri Dec 09 09:48:32.966510 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215: Traceback (most recent call last):
[Fri Dec 09 09:48:32.966614 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215:   File "/var/lib/submin/cgi-bin/submin.cgi", line 8, in <module>
[Fri Dec 09 09:48:32.966676 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215:
[Fri Dec 09 09:48:32.966720 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215: from submin.dispatch.cgirunner import run
[Fri Dec 09 09:48:32.966805 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215: ImportError
[Fri Dec 09 09:48:32.966844 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215: :
[Fri Dec 09 09:48:32.966890 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215: No module named submin.dispatch.cgirunner
[Fri Dec 09 09:48:32.966916 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] AH01215:
[Fri Dec 09 09:48:32.975203 2016] [cgi:error] [pid 13572] [client 10.5.16.80:53112] End of script output before headers: submin.cgi
[Fri Dec 09 09:48:44.758064 2016] [cgi:error] [pid 13573] [client 10.5.16.80:53114] AH01215: Traceback (most recent call last):
[Fri Dec 09 09:48:44.758945 2016] [cgi:error] [pid 13573] [client 10.5.16.80:53114] AH01215:   File "/var/lib/submin/cgi-bin/submin.cgi", line 8, in <module>
[Fri Dec 09 09:48:44.759052 2016] [cgi:error] [pid 13573] [client 10.5.16.80:53114] AH01215:     from submin.dispatch.cgirunner import run
[Fri Dec 09 09:48:44.759143 2016] [cgi:error] [pid 13573] [client 10.5.16.80:53114] AH01215: ImportError: No module named submin.dispatch.cgirunner
[Fri Dec 09 09:48:44.764171 2016] [cgi:error] [pid 13573] [client 10.5.16.80:53114] End of script output before headers: submin.cgi
```

**Comment by mjholtkamp** [comment]
Ugh, that is annoying. It seems something changed in the packaging method.

I'll leave the issue open since it hasn't been fixed, but a workaround currently is:

`ln -s ../site-packages/submin /usr/lib/python2.7/dist-packages/submin`

**Comment by alager** [comment]
That's an easier method than what I ended up doing.  I changed all the config files that referece `dist` to `site`.
